<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Balenthiran.Abstractions/Balenthiran.Abstractions.csproj" />
    <ProjectReference Include="../Balenthiran.EntityModels/Balenthiran.EntityModels.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <EnableDefaultResourceItems>false</EnableDefaultResourceItems>    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
