<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Balenthiran.DomainModels/Balenthiran.DomainModels.csproj" />
    <ProjectReference Include="../Balenthiran.Abstractions/Balenthiran.Abstractions.csproj" />
    <ProjectReference Include="../Balenthiran.Database/Balenthiran.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <EnableDefaultResourceItems>false</EnableDefaultResourceItems>    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
