// <auto-generated />
using System;
using Balenthiran.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Balenthiran.Database.Migrations
{
    [DbContext(typeof(BalenthiranDbContext))]
    [Migration("20260214125549_NormalizeRegisterInterest")]
    partial class NormalizeRegisterInterest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Balenthiran.EntityModels.InterestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubscriberId", "ProjectId")
                        .IsUnique();

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Balenthiran.EntityModels.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General",
                            Slug = "general"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Earn Your Beers",
                            Slug = "earn-your-beers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "APEify",
                            Slug = "apeify"
                        },
                        new
                        {
                            Id = 4,
                            Name = "House Price Alerts",
                            Slug = "house-price-alerts"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Personal Habit Tracker",
                            Slug = "habit-tracker"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Commuter House Search",
                            Slug = "commuter-house-search"
                        });
                });

            modelBuilder.Entity("Balenthiran.EntityModels.SubscriberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Balenthiran.EntityModels.InterestEntity", b =>
                {
                    b.HasOne("Balenthiran.EntityModels.ProjectEntity", "Project")
                        .WithMany("Interests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balenthiran.EntityModels.SubscriberEntity", "Subscriber")
                        .WithMany("Interests")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("Balenthiran.EntityModels.ProjectEntity", b =>
                {
                    b.Navigation("Interests");
                });

            modelBuilder.Entity("Balenthiran.EntityModels.SubscriberEntity", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
